spring.datasource.url: jdbc:mysql://localhost:3306/todolist?serverTimezone=Asia/Yekaterinburg
spring.datasource.username: root
spring.datasource.password: 1321
spring.jpa.hibernate.ddl-auto: create
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl: true
spring.jpa.show-sql: true
server.port: 8084